#!/usr/bin/ksh
#
#
# hit ratio = % buffers found in cache
# Usage :  hitratio <SID>

OSTYPE=$(uname -s)
case $OSTYPE in
"AIX" ) alias bdf="/usr/bin/df -Ik"
        alias ll="/usr/bin/ls -l" ;;
"SunOS") alias bdf="/usr/bin/df -k"
         alias ll="/usr/bin/ls -l"
         alias grep="/usr/xpg4/bin/grep" ;;
"Linux") alias bdf="/bin/df -k"
         alias ll="ls -l" ;;
esac


if [ "$LOGNAME" != "root" ]
then
	if [ -z "$LOGNAME" ]
	then
		:
	else
        	echo "you must launch this script as root"
        	exit 1
	fi
fi

if [ `bdf /tmp|grep tmp|awk '{print $5}'|tr -d %` -ge 98 ]
then
	echo "File system /tmp is full"
	exit 1
fi


if [ $# -ne 1 ]
then
        echo "Usage : $0 <instance name>"
        echo "List of existing instances : \n`grep -v -e "^#" -e "^$" /etc/ORATAB|cut -f1 -d:`"
        exit 1
else
        if grep -q "^$1:" /etc/ORATAB
        then
                echo "\nInstance $1 exists in /etc/ORATAB\n"
        else
                echo "Instance <$1> does not exist Please check"
                echo "List of existing instances : \n`grep -v -e "^#" -e "^$" /etc/ORATAB|cut -f1 -d:`"
                exit 1
        fi
fi

export SID=$1

export  USER=`grep "^$SID:" /etc/ORATAB|cut -d: -f4`
export  OHOME=`grep "^$SID:" /etc/ORATAB|cut -d: -f2`

if [ -x $OHOME/bin/svrmgrl ]
then
        VAR3=svrmgrl
        export VAR4="connect internal"
else
        VAR3="sqlplus -s  \"/ as sysdba \" "
        export VAR4="set wrap off"
        export VAR5="set lines 100"
fi
## csh or ksh
if grep "^$USER:" /etc/passwd|grep -q csh$
then
        export VAR="setenv ORACLE_SID ${SID};setenv ORACLE_HOME ${OHOME}"
        export VAR2="$OHOME/bin/$VAR3 <<EOF >&/dev/null"
else
        export VAR="export ORACLE_SID=${SID};export ORACLE_HOME=${OHOME}"
        export VAR2="$OHOME/bin/$VAR3 <<EOF 1>/dev/null 2>&1"
fi

##
export SYSSTAT=v'\$'sysstat
export STATNAME=v'\$'statname

su - $USER -c "
$VAR
$VAR2
$VAR4
$VAR5
spool /tmp/`basename $0`.log

SELECT DISTINCT
      (TO_NUMBER(s2.value) +
       TO_NUMBER(s3.value) -
       TO_NUMBER(s1.value))/
      (TO_NUMBER(s2.value) +
       TO_NUMBER(s3.value))*100                    hit
FROM   $SYSSTAT                                    s1,
       $SYSSTAT                                    s2,
       $SYSSTAT                                    s3,
       $STATNAME                                   n1,
       $STATNAME                                   n2,
       $STATNAME                                   n3
WHERE  s1.statistic# = n1.statistic#
  AND  s2.statistic# = n2.statistic#
  AND  s3.statistic# = n3.statistic#
  AND  n1.name       = 'physical reads'
  AND  n2.name       = 'consistent gets'
  AND  n3.name       = 'db block gets'
/
spool off
exit
EOF
" >/dev/null

cat /tmp/`basename $0`.log
rm /tmp/`basename $0`.log
