#!/usr/bin/ksh
#
# Script intended to check if tablespace is more than x% full
#
# Usage : $0 monitor_name
# It returns the percentage of use in each tablespace
#
#

if [ -s /etc/PATH ]
then export PATH=$PATH:`cat /etc/PATH`
fi

PROG=`basename $0`
ORATAB=/etc/ORATAB
COUNT=0
PB_COUNT=0
NB_PROC_ALL=0

if [ -s /etc/ORATAB ]
then
    IFS=:
    grep -v "^#" /etc/ORATAB|while read SID ORACLE_HOME FLAG USER
    do

        ## svrmgrl or sqldba
    
               	    if [[ -x $ORACLE_HOME/bin/svrmgrl ]]
               	    then
               		    SQLMGR=svrmgrl
               	    else 
                         if [[ -x $ORACLE_HOME/bin/sqldba ]]
                         then
               		       SQLMGR="sqldba lmode=y"
                         else 
                               : # ORACLE_HOME non existent or empty
                         fi
               	    fi

        ## csh or ksh
	if grep "^$USER:" /etc/passwd|grep csh$
	then
		export VAR="setenv ORACLE_SID ${SID}"
		export VAR2=" $ORACLE_HOME/bin/$SQLMGR <<EOF >&/dev/null"
	else
		export VAR="ORACLE_SID=${SID};export ORACLE_SID"
		export VAR2="$ORACLE_HOME/bin/$SQLMGR <<EOF 1>/dev/null 2>&1"
	fi

export FILEXT=filext'\$'

        ##
	if ps -ef |grep " ora_.*_$SID$"|grep -qv grep # If oracle proc are present
	then
        	su - $USER -c "
        	$VAR
        	$VAR2
        	connect internal
		spool /tmp/`basename $0`.free.log
		select tablespace_name,round(sum(bytes/1024/1024)),file_id
		from dba_free_space
		group by tablespace_name,file_id
		/
		spool off
		spool /tmp/`basename $0`.tot.log
		select tablespace_name, round(sum(bytes/1024/1024)), file_id, file_name
		from dba_data_files
		group by tablespace_name,file_id, file_name
		/
		spool off
		spool /tmp/`basename $0`.auto.log
		select F.file#,F.maxextend,D.file_name
		from $FILEXT F, dba_data_files D
		where F.file#=D.file_id
		/
		spool off
		spool /tmp/`basename $0`.blksz.log
		show parameters db_block_size
		spool off
        	exit;
EOF
        	" 1>/dev/null 2>&1
		if grep -q "ORA-"  /tmp/`basename $0`.blksz.log
			then
				# Oracle not available or other pb
				:
			else
		    		unset IFS
grep -v "row" /tmp/`basename $0`.tot.log|grep -v "^TABLE"|grep -v "^-----"|awk '{print $1$3"\t"$2"\t"$4"\t"$1}' |sort +0 >/tmp/`basename $0`.tot1
grep -v "row" /tmp/`basename $0`.free.log|grep -v "^TABLE"|grep -v "^-----"|awk '{print $1$3"\t"$2}' |sort +0 >/tmp/`basename $0`.free1
grep -v "row" /tmp/`basename $0`.auto.log|grep -v "^FILE"|grep -v "^-----"|awk '{print $2"\t"$3}' >/tmp/`basename $0`.auto1
export BLKSZ=`grep -v "^NAME" /tmp/\`basename $0\`.blksz.log|grep -v "^-----"|awk '{print $3}'`

export INI_TN=tablespace
export MIN_PERCENTAGE=100

join -j1 1 -j2 1 -a 1 -e 0 -o 1.1,1.2,2.2,1.3,1.4 /tmp/`basename $0`.tot1 /tmp/`basename $0`.free1| while read TN TT TA FN TN
do
	(( TU = $TT - $TA ))
	if [[ ${TN} = ${INI_TN} ]]
	# Same tablespace
	then
		if grep ${FN}$ /tmp/`basename $0`.auto1|read MAX FNbis
		then
		# file in autoextend mode
			if [ $MAX -eq 4194302 ]
			then
			# unlimited
				PCT_USE=`bdf ${FN} |grep -v ^Filesystem | awk '{print $5}'|tr -d %`
				OBJECT="TS_unlimited"
			else
			# autoextend limited
				(( TT = ${MAX} * ${BLKSZ} / 1024 / 1024 ))
				OBJECT="TS_limited"
				PCT_USE=`bc -l <<EOF
scale=2
$TU/$TT*100
EOF`
			fi
		else
		# file NOT in autoextend mode
		OBJECT="TS_standard"
        PCT_USE=`bc -l <<EOF
scale=2
$TU/$TT*100
EOF`
		fi
		if [ ${PCT_USE} -lt ${MIN_PERCENTAGE} ]
		then
			MIN_PERCENTAGE=${PCT_USE}
		fi
	else
		if [ ${INI_TN} != "tablespace" ]
		then 
       			opcmon $1=${MIN_PERCENTAGE} -object $OBJECT -option SID=$SID -option TABLESPACE=${INI_TN}
		fi
	
		INI_TN=${TN}
		MIN_PERCENTAGE=100
		if grep ${FN}$ /tmp/`basename $0`.auto1|read MAX FNbis
                then
                # file in autoextend mode
                        if [ $MAX -eq 4194302 ]
                        then
                        # unlimited
                                PCT_USE=`bdf ${FN} |grep -v ^Filesystem | awk '{print $5}'|tr -d %`
                                OBJECT="TS_unlimited"
                        else
                        # autoextend limited
                                (( TT = ${MAX} * ${BLKSZ} / 1024 / 1024 ))
                                OBJECT="TS_limited"
                                PCT_USE=`bc -l <<EOF
scale=2
$TU/$TT*100
EOF`
                        fi
                else
                # file NOT in autoextend mode
                OBJECT="TS_standard"
        	PCT_USE=`bc -l <<EOF
scale=2
$TU/$TT*100
EOF`
                fi
                if [ ${PCT_USE} -lt ${MIN_PERCENTAGE} ]
                then
                        MIN_PERCENTAGE=${PCT_USE}
                fi
	fi
done
#rm /tmp/`basename $0`.free.log
#rm /tmp/`basename $0`.free1
#rm /tmp/`basename $0`.tot.log
#rm /tmp/`basename $0`.tot1

		fi
	IFS=:
	fi
    done
        
    unset IFS
fi

# Returns 0 % of use if no oracle installed or no archive mode or script pb
opcmon "$1=0"
