#!/usr/bin/ksh
#
# purge 2PC lost db entry
# Usage :  $0 <sid> 

OSTYPE=$(uname -s)
case $OSTYPE in
"AIX" ) alias bdf="/usr/bin/df -Ik"
        alias ll="/usr/bin/ls -l" ;;
"SunOS") alias bdf="/usr/bin/df -k"
         alias ll="/usr/bin/ls -l"
         alias grep="/usr/xpg4/bin/grep" ;;
"Linux") alias bdf="/bin/df -k"
         alias ll="ls -l" ;;
esac


if [ "$LOGNAME" != "root" ]
then
	if [ -z "$LOGNAME" ]
	then
		:
	else
        	echo "you must launch this script as root"
        	exit 1
	fi
fi


if [ $# -ne 1 ]
then
        echo "Usage : $0 <instance name>"
        echo "List of existing instances : \n`grep -v -e "^#" -e "^$" /etc/ORATAB|cut -f1 -d:`"
        exit 1
else
        if grep -q "^$1:" /etc/ORATAB
        then
                echo "\nInstance $1 exists in /etc/ORATAB\n"
        else
                echo "Instance <$1> does not exist Please check"
                echo "List of existing instances : \n`grep -v -e "^#" -e "^$" /etc/ORATAB|cut -f1 -d:`"
                exit 1
        fi
fi


export SID=$1

if [ `bdf /tmp|grep tmp|awk '{print $5}'|tr -d %` -ge 98 ]
then
	echo "File system /tmp is full"
	exit 1
fi

export  USER=`grep "^$SID:" /etc/ORATAB|cut -d: -f4`
export  OHOME=`grep "^$SID:" /etc/ORATAB|cut -d: -f2`


if [ -x $OHOME/bin/svrmgrl ]
then
        VAR3=svrmgrl
        export VAR4="connect internal"
else
        VAR3="sqlplus -s  \"/ as sysdba \" "
        export VAR4="set wrap on"
        export VAR5="set lines 200"
fi
## csh or ksh
if grep "^$USER:" /etc/passwd|grep -q csh$
then
        export VAR="setenv ORACLE_SID ${SID};setenv ORACLE_HOME ${OHOME}"
        export VAR2="$OHOME/bin/$VAR3 <<EOF >&/dev/null"
else
        export VAR="export ORACLE_SID=${SID};export ORACLE_HOME=${OHOME}"
        export VAR2="$OHOME/bin/$VAR3 <<EOF 1>/dev/null 2>&1"
fi

##
su - $USER -c "
$VAR
$VAR2
$VAR4
$VAR5
alter session set nls_date_format='DD-MON-YYYY HH24:MI:SS';
set datewidth 20
spool /tmp/`basename $0`.log
select * from dba_2pc_pending;
spool off
exit;
EOF
" 1>/dev/null 2>&1

echo "			List of current pending transaction"
echo "			===================================\n"
cat /tmp/`basename $0`.log

echo "Please enter Trans ID to remove it or type <return> : \c"
read TRID
if [ "${TRID}x" = "x" ] ; then
	rm /tmp/`basename $0`.log
	echo nothing to purge
	exit
fi
export TRID

su - $USER -c "
$VAR
$VAR2
$VAR4
$VAR5
spool /tmp/`basename $0`.log
rollback force '${TRID}';
alter session set "_smu_debug_mode" = 4;
execute dbms_transaction.purge_lost_db_entry('${TRID}');
spool off
exit;
EOF
" >/dev/null 

rm /tmp/`basename $0`.log
