#!/bin/ksh
#
# Displaying session activity taken or requested by non-kernel sessions
#

USAGE=$(cat <<!
\n\tUsage: $(basename $0) instance [and-where-clause] \n
  \tDesc : \tdisplaying user session activity on a chosen database on current node \n
  \tOpts : \tand-where-clause: SQL clause beginning with 'and' like examples below:\n
  \t       \t"and OSUSER='osuser'" ; "and process='PID'" ; "and SCHEMANAME='db-user'" \n
  \tArgs just used: $*\n
!)

# Arg number check
if [ $# -lt 1 ]
then
    echo $USAGE; exit 1
fi

# functions library and common fixed variables PATH,CFG
. $(dirname $0)/IamAdbTool.env

# Fixed parans
MAIN=$(basename $0)
# defaults
SQL=NO
KEEP=""    # empty option

# overloading db name param (compatibility with IamAdbTool.env)
DB_NAME=$1
shift
# prevent file name generation
set -f
WHERE="$*"

# osuser behaviour
if [ "$OSUSER" = "" ]
then
    # default: exclude myself to avoid seeing this script's request
    USERWHERE="and osuser != '"$(whoami)"'"
else
    if [ "$OSUSER" = "ALL" ]
    then
        USERWHERE=""
    else
        # value provided: select only one user
        USERWHERE="and osuser = '"$OSUSER"'"
    fi
fi
# default columns
if [ "$COLS" = "" ]
then
    if [ "$SQL" = "YES" ]
    then
        if [ "$SHORTOUTPUT" = "YES" ]
        then
            COLS="substr('SID: '||SID||' '||schemaname||' '||ltrim(rtrim(machine))||'  PID: '||process,1,40) as PID_on_machine_and_SID_owner"
        else
            COLS="machine||'  PID: '||process,substr(schemaname,1,10),osuser,TERMINAL,PROGRAM,command,module"
        fi
    else
        COLS="SID,osuser,substr(schemaname,1,10),lockwait,status,PROGRAM,module"
    fi
fi

# compose process/user info, forget PID if NT connection
COLS="'SID: '||SID||' '||decode(instr(process,':'),0,'PID: '||process,-1,'error',program)||' '||schemaname||' on '||ltrim(rtrim(machine)) as PID_on_machine_and_SID_owner"

sql $DB_NAME "SELECT t.SQL_TEXT, $COLS from V\$SESSION s, V\$SQLTEXT t where t.address = SQL_ADDRESS and t.HASH_VALUE = SQL_HASH_VALUE and s.type='USER' $USERWHERE $WHERE order by s.sid,t.piece;" |cut -c 5-

### end of script
